Title: Chih-Ming Louis Lee

Theme: minimal

Menu:
    Home: plain
    Resume: plain
    Research: plain
    Project: plain
    Blog: plain

Home:
    main: [intro]

intro:
    image: image/test_photo.jpg
    text: "I am an undergraduate majoring Political Science and Mathematics in [University of Illinois Urbana-Champaign](https://illinois.edu/). I focus on comparative politics and political methodology. In particular, I'm interested in ethnic ideneity and formal modeling. \n

I am also a research assistant of [Cline Center for Advance Social Research](https://clinecenter.illinois.edu/), working on Composition of Religious and Ethnic Group (CREG) Project. \n

Download my resume [here](../file/resume.pdf). You can contant me at [email]() or follow me on [GitHub](https://github.com/chmlee) and [Twitter](https://twiter.com/chmlee1202)."

footer:
    text: "Powered by [Vanilla](#)"

